apiVersion: apps/v1
kind: Deployment
metadata:
  name: pd-k8s-api-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pd-k8s-api-a-label
  template:
    metadata:
      labels:
        app: pd-k8s-api-a-label
    spec:
      containers:
      - name: pd-k8s-api-a-container
        image: pdesaidocker/k8sapia:v2
        ports:
        - containerPort: 8080 #port defined in image dockerfile
        env:  # Add environment variables here
        - name: apib-service-url
          value: "http://pd-k8s-api-b-net-service:90/api/ApiB"  # Set the environment variable