apiVersion: v1
kind: Service
metadata:
  name: pd-k8s-api-b-net-service
  namespace: prod
spec:
  selector:
    app: pd-k8s-api-b-label  # This selector should match the labels of the Pods
    environment: prod
  ports:
  - port: 91  # Port on the Service
    targetPort: 8080  # Port on the Pod
